### ISSUE TITLE
Feature Request: change font

### ISSUE THREAD

**Issue by nubesurrealista** [MaintainTeam/LastPipeBender#10]
First of all: good luck with this project, I think it has a **future**.

Since the roadmap talks about implementing requested features in Newpipe or Tubular, I just wanted you to take a look at this [PR](First of all: good luck with this project, I think it has a future.

Since the roadmap talks about implementing requested features in Newpipe or Tubular, I just wanted you to take a look at this [PR](https://github.com/TeamNewPipe/NewPipe/pull/11645) To add a font change option 👀

I'll understand if you're not interested, Well, thanks for the good work!

**Comment by asandikci** [comment]
Thanks 😊 

PR seems good and reasonably NewPipe team does not want to add it because of the **rewrite process** of app. I respect the situation of team/project. Also I don't want to make this app a *hard fork* (if I merge this PR now and NewPipe team are going to implement this feature in a different way later, this will cause to collision between projects) So It is better to not adding this feature to main branch.

I am going to merge this feature to `extended` branch only for now. After the that I am planning to publish a new **pre-version** with different tag like `v0.27.4 RC1`

Is it suitable for you?

**Comment by nubesurrealista** [comment]
> Is it suitable for you?

Sound's interesting 👀

Thanks for the reply!

**Comment by asandikci** [comment]
updated readme, see: https://github.com/MaintainTeam/LastPipeBender?tab=readme-ov-file#project-management

**Comment by asandikci** [comment]
@nubesurrealista merged and built the apk
Could you please test this apk: [app.zip](https://github.com/user-attachments/files/18030595/app.zip)

this is a debug version, it is foreseen that app can be slower
You can see the font setting in `Content > App Font` setting

**Comment by asandikci** [comment]
! the app is not stable and font implementation is not app-wide yet !

see: https://github.com/TeamNewPipe/NewPipe/pull/11645#issuecomment-2521693678

**Comment by nubesurrealista** [comment]
[16e51d0c-ebab-40cd-b24e-5f87fee5cbed(1).webm](https://github.com/user-attachments/assets/6688394a-4ca4-4b36-9613-628137650ed2)

Thanks for trying!!. Yep, it crashed for me:

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ ES
* __Content Language:__ es-ES
* __App Language:__ es_ES
* __Service:__ none
* __Version:__ 0.27.4
* __OS:__ Linux TCL/5033E/U3A_PLUS_4G:8.1.0/O11019/v7L81-0:user/release-keys 8.1.0 - 27
<details><summary><b>Crash log </b></summary><p>

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.maintainteam.lastpipebender.debug.featurerequestchangefont/org.schabi.newpipe.MainActivity}: java.lang.RuntimeException: Already configured. build() must be last invoked method.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2937)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3015)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6666)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: java.lang.RuntimeException: Already configured. build() must be last invoked method.
	at com.marcinorlowski.fonty.Fonty$Companion.failIfConfigured(Fonty.kt:394)
	at com.marcinorlowski.fonty.Fonty$Companion.context(Fonty.kt:340)
	at com.marcinorlowski.fonty.Fonty.context(Unknown Source:2)
	at org.schabi.newpipe.MainActivity.setUpFont(MainActivity.java:215)
	at org.schabi.newpipe.MainActivity.onCreate(MainActivity.java:136)
	at android.app.Activity.performCreate(Activity.java:7029)
	at android.app.Activity.performCreate(Activity.java:7020)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2890)
	... 9 more

```
</details>
<hr>

**Comment by asandikci** [comment]
I don't know the reason for now. I'll **later** try with pure NewPipe + this PR and see what is going on.

**Comment by asandikci** [comment]
Tried with pure NewPipe and issue still persist. So the problem is PR. It should be fixed by the author. I can try fixing it in my free time but no promise

pinging PR author: @u7648330

pure NewPipe + this PR: [app(1).zip](https://github.com/user-attachments/files/18039153/app.1.zip) (still has same error but maybe you want to test this version also)

**Comment by brnwlshubh** [comment]
@asandikci Did you see [this](https://github.com/u7648330/NewPipe/pull/1)... as this got merged by the author?

**Comment by asandikci** [comment]
I'have already merged this PR. But author committed 2 more commits after merged it into his/her own dev branch. I'll try directly merging from author's dev branch. Thanks for heads up!

**Comment by asandikci** [comment]
unfortunately still gives same error :(

**Comment by asandikci** [comment]
Tried to implement this feature as a separate file (util/FontManager.java) but could not get any successful build unfortunately. I gave up for now

**Comment by u7648330** [comment]
hi sorry have just seen this, may I ask what the current problem is and how I can help?

**Comment by asandikci** [comment]
@u7648330 no problem.

There is an error when changing the font. You can see crash log below: https://github.com/MaintainTeam/LastPipeBender/issues/10#issuecomment-2521716063

Shortly: `Caused by: java.lang.RuntimeException: Already configured. build() must be last invoked method.`

Tried both with this fork (LastPipeBender) and original Newpipe latest dev branch with merging your commits and there is same issue in both.

Some users see this error in first app start after changing the font. I see this error after changing video source (youtube -> soundcloud for example)

Possibly error caused because of font build functions called multiple times. I'm not sure

I built both app as "debug" version and you can see the build command in `.github/workflows/ci.yml` in this repo.

`10-feature-request-change-font` branch is where I merged your commits and maybe you can take a look? Or better It would be good to update your PR in original NewPipe project and make sure the compatibility with latest version.

Ping me if any further information is needed
Thanks in advance!
