### ISSUE TITLE
Crash when adding videos to queue from different channel groups after refresh

### ISSUE THREAD

**Issue by asandikci** [MaintainTeam/LastPipeBender#11]
- [ ] needs to be tested with NewPipe/Tubular to know if it is specific to this project

### Steps to reproduce
- select a video from a channel group and start to play it
- after open **another** channel group and refresh it (fetch latest videos)
- select a new(?) video from this group and add it to queue
- make currently playing video fullscreen (?)
- exit from fullscreen and back to main menu (while video still playing)
- app crash

## Exception
* __User Action:__ ui error
* __Request:__ ACRA report
* __Content Country:__ TR
* __Content Language:__ en-
* __App Language:__ en_GB
* __Service:__ none
* __Version:__ 0.27.4
* __OS:__ Linux samsung/on7xrefltedd/on7xreflte:9/PPR1.180610.011/G611FXXU1CSE2:user/release-keys 9 - 28
<details><summary><b>Crash log </b></summary><p>

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at android.widget.Toast.makeText(Toast.java:680)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:192)
	at org.schabi.newpipe.util.NavigationHelper.enqueueOnPlayer(NavigationHelper.java:206)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.lambda$static$2(StreamDialogDefaultEntry.java:54)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry.$r8$lambda$a5xl77Dbtzjng57a7aWTqc2QHLM(StreamDialogDefaultEntry.java:0)
	at org.schabi.newpipe.info_list.dialog.StreamDialogDefaultEntry$$ExternalSyntheticLambda17.accept(R8$$SyntheticClass:0)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchItemInfoIfSparse$0(SparseItemUtil.java:60)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$gVp-oj4sCNUa5XRwqzA5fQ53LU0(SparseItemUtil.java:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda1.accept(R8$$SyntheticClass:0)
	at org.schabi.newpipe.util.SparseItemUtil.lambda$fetchStreamInfoAndSaveToDatabase$4(SparseItemUtil.java:121)
	at org.schabi.newpipe.util.SparseItemUtil.$r8$lambda$deU_krLKc2Rq-Kx27FrpNhdkTCk(SparseItemUtil.java:0)
	at org.schabi.newpipe.util.SparseItemUtil$$ExternalSyntheticLambda2.accept(R8$$SyntheticClass:0)
	at io.reactivex.rxjava3.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
	at io.reactivex.rxjava3.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7127)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```
</details>
<hr>

**Comment by asandikci** [comment]
Is anyone can reproduce this? It sometimes occurs sometimes not. Probably I miss a step. 

And is there any similar error on NewPipe/Tubular?

**Comment by whistlingwoods** [comment]
Does this comment helps debugging this?https://github.com/TeamNewPipe/NewPipe/issues/9609#issuecomment-1368141628

**Comment by asandikci** [comment]
@whistlingwoods Thanks for the suggestions and sources. I'll investigate in my free time.
